/*
 * generated by Xtext
 */
package io.pelle.mango.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MangoRuntimeModule extends io.pelle.mango.dsl.AbstractMangoRuntimeModule {

}
