/*
 * generated by Xtext
 */
package io.pelle.mango.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MangoUiModule extends io.pelle.mango.dsl.ui.AbstractMangoUiModule {
	public MangoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
