/**
 * generated by Xtext
 */
package io.pelle.mango.dsl.generator.client.dictionary;

import com.google.common.base.CaseFormat;
import io.pelle.mango.dsl.ModelUtil;
import io.pelle.mango.dsl.generator.client.ClientNameUtils;
import io.pelle.mango.dsl.mango.Dictionary;
import io.pelle.mango.dsl.mango.DictionaryContainer;
import io.pelle.mango.dsl.mango.DictionaryControl;
import io.pelle.mango.dsl.mango.DictionaryEditor;
import io.pelle.mango.dsl.mango.DictionaryFilter;
import io.pelle.mango.dsl.mango.DictionaryResult;
import io.pelle.mango.dsl.mango.DictionarySearch;
import io.pelle.mango.dsl.mango.Model;
import io.pelle.mango.dsl.mango.NavigationNode;
import org.eclipse.xtext.xbase.lib.StringExtensions;

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
@SuppressWarnings("all")
public class DictionaryNameUtils extends ClientNameUtils {
  public String camelCaseToUnderScore(final String camelCase) {
    return CaseFormat.UPPER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, camelCase);
  }
  
  public String constantName(final String constant) {
    String _camelCaseToUnderScore = this.camelCaseToUnderScore(constant);
    return _camelCaseToUnderScore.toUpperCase();
  }
  
  public String dictionaryClassName(final Model model) {
    String _name = model.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name);
    return (_firstUpper + "DictionaryModel");
  }
  
  public String dictionaryClassFullQualifiedName(final Model model) {
    String _modelPackageName = this.modelPackageName(model);
    String _plus = (_modelPackageName + ".");
    String _dictionaryClassName = this.dictionaryClassName(model);
    return (_plus + _dictionaryClassName);
  }
  
  public String dictionaryClassFullQualifiedFileName(final Model model) {
    String _dictionaryClassFullQualifiedName = this.dictionaryClassFullQualifiedName(model);
    String _replaceAll = _dictionaryClassFullQualifiedName.replaceAll("\\.", "/");
    return (_replaceAll + ".java");
  }
  
  public String dictionaryClassName(final Dictionary dictionary) {
    String _name = dictionary.getName();
    return StringExtensions.toFirstUpper(_name);
  }
  
  public String dictionaryClassFullQualifiedName(final Dictionary dictionary) {
    String _packageName = this.getPackageName(dictionary);
    String _plus = (_packageName + ".");
    String _dictionaryClassName = this.dictionaryClassName(dictionary);
    return (_plus + _dictionaryClassName);
  }
  
  public String dictionaryClassFullQualifiedFileName(final Dictionary dictionary) {
    String _dictionaryClassFullQualifiedName = this.dictionaryClassFullQualifiedName(dictionary);
    String _replaceAll = _dictionaryClassFullQualifiedName.replaceAll("\\.", "/");
    return (_replaceAll + ".java");
  }
  
  public String dictionaryConstantName(final Dictionary dictionary) {
    String _name = dictionary.getName();
    String _constantName = this.constantName(_name);
    return _constantName;
  }
  
  public String navigationNodeClassName(final NavigationNode navigationNode) {
    String _name = navigationNode.getName();
    return StringExtensions.toFirstUpper(_name);
  }
  
  public String navigationyNodeClassFullQualifiedName(final NavigationNode navigationNode) {
    String _packageName = this.getPackageName(navigationNode);
    String _plus = (_packageName + ".");
    String _navigationNodeClassName = this.navigationNodeClassName(navigationNode);
    return (_plus + _navigationNodeClassName);
  }
  
  public String navigationNodeClassFullQualifiedFileName(final NavigationNode navigationNode) {
    String _navigationyNodeClassFullQualifiedName = this.navigationyNodeClassFullQualifiedName(navigationNode);
    String _replaceAll = _navigationyNodeClassFullQualifiedName.replaceAll("\\.", "/");
    return (_replaceAll + ".java");
  }
  
  public String navigationNodeConstantName(final NavigationNode navigationNode) {
    String _name = navigationNode.getName();
    String _constantName = this.constantName(_name);
    return _constantName;
  }
  
  public String navigationNodeClassName(final Model model) {
    String _name = model.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name);
    return (_firstUpper + "NavigationModel");
  }
  
  public String navigationyNodeClassFullQualifiedName(final Model model) {
    String _modelPackageName = this.modelPackageName(model);
    String _plus = (_modelPackageName + ".");
    String _navigationNodeClassName = this.navigationNodeClassName(model);
    return (_plus + _navigationNodeClassName);
  }
  
  public String navigationNodeClassFullQualifiedFileName(final Model model) {
    String _navigationyNodeClassFullQualifiedName = this.navigationyNodeClassFullQualifiedName(model);
    String _replaceAll = _navigationyNodeClassFullQualifiedName.replaceAll("\\.", "/");
    return (_replaceAll + ".java");
  }
  
  public String dictionaryClassName(final DictionaryEditor dictionaryEditor) {
    String _name = dictionaryEditor.getName();
    return StringExtensions.toFirstUpper(_name);
  }
  
  public String dictionaryClassFullQualifiedName(final DictionaryEditor dictionaryEditor) {
    String _packageName = this.getPackageName(dictionaryEditor);
    String _plus = (_packageName + ".");
    String _dictionaryClassName = this.dictionaryClassName(dictionaryEditor);
    return (_plus + _dictionaryClassName);
  }
  
  public String dictionaryClassFullQualifiedFileName(final DictionaryEditor dictionaryEditor) {
    String _dictionaryClassFullQualifiedName = this.dictionaryClassFullQualifiedName(dictionaryEditor);
    String _replaceAll = _dictionaryClassFullQualifiedName.replaceAll("\\.", "/");
    return (_replaceAll + ".java");
  }
  
  public String dictionaryConstantName(final DictionaryEditor dictionaryEditor) {
    String _name = dictionaryEditor.getName();
    String _constantName = this.constantName(_name);
    return _constantName;
  }
  
  public String dictionaryClassName(final DictionarySearch dictionarySearch) {
    String _name = dictionarySearch.getName();
    return StringExtensions.toFirstUpper(_name);
  }
  
  public String dictionaryClassFullQualifiedName(final DictionarySearch dictionarySearch) {
    String _packageName = this.getPackageName(dictionarySearch);
    String _plus = (_packageName + ".");
    String _dictionaryClassName = this.dictionaryClassName(dictionarySearch);
    return (_plus + _dictionaryClassName);
  }
  
  public String dictionaryClassFullQualifiedFileName(final DictionarySearch dictionarySearch) {
    String _dictionaryClassFullQualifiedName = this.dictionaryClassFullQualifiedName(dictionarySearch);
    String _replaceAll = _dictionaryClassFullQualifiedName.replaceAll("\\.", "/");
    return (_replaceAll + ".java");
  }
  
  public String dictionaryConstantName(final DictionarySearch dictionarySearch) {
    String _name = dictionarySearch.getName();
    String _constantName = this.constantName(_name);
    return _constantName;
  }
  
  public String dictionaryClassName(final DictionaryFilter dictionaryFilter) {
    String _name = dictionaryFilter.getName();
    return StringExtensions.toFirstUpper(_name);
  }
  
  public String dictionaryClassFullQualifiedName(final DictionaryFilter dictionaryFilter) {
    String _packageName = this.getPackageName(dictionaryFilter);
    String _plus = (_packageName + ".");
    String _dictionaryClassName = this.dictionaryClassName(dictionaryFilter);
    return (_plus + _dictionaryClassName);
  }
  
  public String dictionaryClassFullQualifiedFileName(final DictionaryFilter dictionaryFilter) {
    String _dictionaryClassFullQualifiedName = this.dictionaryClassFullQualifiedName(dictionaryFilter);
    String _replaceAll = _dictionaryClassFullQualifiedName.replaceAll("\\.", "/");
    return (_replaceAll + ".java");
  }
  
  public String dictionaryConstantName(final DictionaryFilter dictionaryFilter) {
    String _name = dictionaryFilter.getName();
    String _constantName = this.constantName(_name);
    return _constantName;
  }
  
  public String dictionaryClassName(final DictionaryResult dictionaryResult) {
    String _name = dictionaryResult.getName();
    return StringExtensions.toFirstUpper(_name);
  }
  
  public String dictionaryClassFullQualifiedName(final DictionaryResult dictionaryResult) {
    String _packageName = this.getPackageName(dictionaryResult);
    String _plus = (_packageName + ".");
    String _dictionaryClassName = this.dictionaryClassName(dictionaryResult);
    return (_plus + _dictionaryClassName);
  }
  
  public String dictionaryClassFullQualifiedFileName(final DictionaryResult dictionaryResult) {
    String _dictionaryClassFullQualifiedName = this.dictionaryClassFullQualifiedName(dictionaryResult);
    String _replaceAll = _dictionaryClassFullQualifiedName.replaceAll("\\.", "/");
    return (_replaceAll + ".java");
  }
  
  public String dictionaryConstantName(final DictionaryResult dictionaryResult) {
    String _name = dictionaryResult.getName();
    String _constantName = this.constantName(_name);
    return _constantName;
  }
  
  public String dictionaryClassName(final DictionaryControl dictionaryControl) {
    String _name = dictionaryControl.getName();
    return StringExtensions.toFirstUpper(_name);
  }
  
  public String dictionaryClassFullQualifiedName(final DictionaryControl dictionaryControl) {
    String _packageName = this.getPackageName(dictionaryControl);
    String _plus = (_packageName + ".");
    String _dictionaryClassName = this.dictionaryClassName(dictionaryControl);
    return (_plus + _dictionaryClassName);
  }
  
  public String dictionaryClassFullQualifiedFileName(final DictionaryControl dictionaryControl) {
    String _dictionaryClassFullQualifiedName = this.dictionaryClassFullQualifiedName(dictionaryControl);
    String _replaceAll = _dictionaryClassFullQualifiedName.replaceAll("\\.", "/");
    return (_replaceAll + ".java");
  }
  
  public String dictionaryConstantName(final DictionaryControl dictionaryControl) {
    String _controlName = ModelUtil.getControlName(dictionaryControl);
    String _constantName = this.constantName(_controlName);
    return _constantName;
  }
  
  public String dictionaryClassName(final DictionaryContainer dictionaryContainer) {
    String _name = dictionaryContainer.getName();
    return StringExtensions.toFirstUpper(_name);
  }
  
  public String dictionaryClassFullQualifiedName(final DictionaryContainer dictionaryContainer) {
    String _packageName = this.getPackageName(dictionaryContainer);
    String _plus = (_packageName + ".");
    String _dictionaryClassName = this.dictionaryClassName(dictionaryContainer);
    return (_plus + _dictionaryClassName);
  }
  
  public String dictionaryClassFullQualifiedFileName(final DictionaryContainer dictionaryContainer) {
    String _dictionaryClassFullQualifiedName = this.dictionaryClassFullQualifiedName(dictionaryContainer);
    String _replaceAll = _dictionaryClassFullQualifiedName.replaceAll("\\.", "/");
    return (_replaceAll + ".java");
  }
  
  public String dictionaryConstantName(final DictionaryContainer dictionaryContainer) {
    String _name = dictionaryContainer.getName();
    String _constantName = this.constantName(_name);
    return _constantName;
  }
}
