/**
 * generated by Xtext
 */
package io.pelle.mango.dsl.generator.client;

import com.google.inject.Inject;
import io.pelle.mango.dsl.generator.client.ClientNameUtils;
import org.eclipse.xtext.xbase.lib.Extension;

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
@SuppressWarnings("all")
public class ClientAttributeUtils {
  @Inject
  @Extension
  private ClientNameUtils _clientNameUtils;
}
