/*
 * generated by Xtext
 */
package io.pelle.mango.dsl.validation;

import io.pelle.mango.dsl.ModelUtil;
import io.pelle.mango.dsl.mango.DictionaryReferenceControl;
import io.pelle.mango.dsl.mango.MangoPackage;

import org.eclipse.xtext.validation.Check;

/**
 * Custom validation rules.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
public class MangoJavaValidator extends io.pelle.mango.dsl.validation.AbstractMangoJavaValidator {

	// @Check
	// public void checkGreetingStartsWithCapital(Greeting greeting) {
	// if (!Character.isUpperCase(greeting.getName().charAt(0))) {
	// warning("Name should start with a capital",
	// MyDslPackage.Literals.GREETING__NAME);
	// }
	// }

	@Check
	public void checkGreetingStartsWithCapital(DictionaryReferenceControl referenceControl) {

		if (referenceControl.getRef() == null) {
			if (referenceControl.getDictionary() == null) {
				error("no dictionary specified", referenceControl, MangoPackage.Literals.DICTIONARY_REFERENCE_CONTROL__DICTIONARY);
			}
		} else {
			if (ModelUtil.getReferenceControlDictionary(referenceControl) == null) {
				error("no dictionary specified in control hierarchy", referenceControl, MangoPackage.Literals.DICTIONARY_REFERENCE_CONTROL__DICTIONARY);
			}

		}
	}
}
