/*
 * generated by Xtext
 */
package io.pelle.mango.dsl.generator.client

import com.google.inject.Inject

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
class ClientAttributeUtils {

	@Inject
	extension ClientNameUtils

}
