/*
* generated by Xtext
*/
package io.pelle.mango.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MangoStandaloneSetup extends MangoStandaloneSetupGenerated{

	public static void doSetup() {
		new MangoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

