/*
 * generated by Xtext
 */
package io.pelle.mango.dsl.generator.client.dictionary

import com.google.common.base.CaseFormat
import io.pelle.mango.dsl.ModelUtil
import io.pelle.mango.dsl.generator.client.ClientNameUtils
import io.pelle.mango.dsl.mango.Dictionary
import io.pelle.mango.dsl.mango.DictionaryContainer
import io.pelle.mango.dsl.mango.DictionaryControl
import io.pelle.mango.dsl.mango.DictionaryEditor
import io.pelle.mango.dsl.mango.DictionaryFilter
import io.pelle.mango.dsl.mango.DictionaryResult
import io.pelle.mango.dsl.mango.DictionarySearch
import io.pelle.mango.dsl.mango.Model
import io.pelle.mango.dsl.mango.NavigationNode

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
class DictionaryNameUtils extends ClientNameUtils {

	def camelCaseToUnderScore(String camelCase) {
		return CaseFormat.UPPER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, camelCase);
	}

	def constantName(String constant) {
		return constant.camelCaseToUnderScore.toUpperCase
	}
	
	//-------------------------------------------------------------------------
	// Model
	//-------------------------------------------------------------------------
	def dictionaryClassName(Model model) {
		return model.name.toFirstUpper() + "DictionaryModel";
	}

	def dictionaryClassFullQualifiedName(Model model) {
		return model.modelPackageName + '.' + model.dictionaryClassName;
	}

	def dictionaryClassFullQualifiedFileName(Model model) {
		return model.dictionaryClassFullQualifiedName.replaceAll("\\.", "/")  + ".java";
	}

	//-------------------------------------------------------------------------
	// Dictionary
	//-------------------------------------------------------------------------
	def dictionaryClassName(Dictionary dictionary) {
		return dictionary.name.toFirstUpper();
	}

	def dictionaryClassFullQualifiedName(Dictionary dictionary) {
		return dictionary.packageName + '.' + dictionary.dictionaryClassName;
	}

	def dictionaryClassFullQualifiedFileName(Dictionary dictionary) {
		return dictionary.dictionaryClassFullQualifiedName.replaceAll("\\.", "/")  + ".java";
	}

	def dictionaryConstantName(Dictionary dictionary) {
		dictionary.name.constantName
	}

	//-------------------------------------------------------------------------
	// NavigationNode
	//-------------------------------------------------------------------------
	def navigationNodeClassName(NavigationNode navigationNode) {
		return navigationNode.name.toFirstUpper;
	}

	def navigationyNodeClassFullQualifiedName(NavigationNode navigationNode) {
		return navigationNode.packageName + '.' + navigationNode.navigationNodeClassName;
	}

	def navigationNodeClassFullQualifiedFileName(NavigationNode navigationNode) {
		return navigationNode.navigationyNodeClassFullQualifiedName.replaceAll("\\.", "/")  + ".java";
	}

	def navigationNodeConstantName(NavigationNode navigationNode) {
		navigationNode.name.constantName
	}

	//-------------------------------------------------------------------------
	// Navigation
	//-------------------------------------------------------------------------
	def navigationNodeClassName(Model model) {
		return model.name.toFirstUpper + "NavigationModel";
	}

	def navigationyNodeClassFullQualifiedName(Model model) {
		return model.modelPackageName + '.' + model.navigationNodeClassName;
	}

	def navigationNodeClassFullQualifiedFileName(Model model) {
		return model.navigationyNodeClassFullQualifiedName.replaceAll("\\.", "/")  + ".java";
	}
	
	//-------------------------------------------------------------------------
	// DictionaryEditor
	//-------------------------------------------------------------------------
	def dictionaryClassName(DictionaryEditor dictionaryEditor) {
		return dictionaryEditor.name.toFirstUpper();
	}

	def dictionaryClassFullQualifiedName(DictionaryEditor dictionaryEditor) {
		return dictionaryEditor.packageName + '.' + dictionaryEditor.dictionaryClassName;
	}

	def dictionaryClassFullQualifiedFileName(DictionaryEditor dictionaryEditor) {
		return dictionaryEditor.dictionaryClassFullQualifiedName.replaceAll("\\.", "/")  + ".java";
	}

	def dictionaryConstantName(DictionaryEditor dictionaryEditor) {
		dictionaryEditor.name.constantName
	}

	//-------------------------------------------------------------------------
	// DictionarySearch
	//-------------------------------------------------------------------------
	def dictionaryClassName(DictionarySearch dictionarySearch) {
		return dictionarySearch.name.toFirstUpper();
	}

	def dictionaryClassFullQualifiedName(DictionarySearch dictionarySearch) {
		return dictionarySearch.packageName + '.' + dictionarySearch.dictionaryClassName;
	}

	def dictionaryClassFullQualifiedFileName(DictionarySearch dictionarySearch) {
		return dictionarySearch.dictionaryClassFullQualifiedName.replaceAll("\\.", "/")  + ".java";
	}

	def dictionaryConstantName(DictionarySearch dictionarySearch) {
		dictionarySearch.name.constantName
	}
	
	//-------------------------------------------------------------------------
	// DictionaryFilter
	//-------------------------------------------------------------------------
	def dictionaryClassName(DictionaryFilter dictionaryFilter) {
		return dictionaryFilter.name.toFirstUpper();
	}

	def dictionaryClassFullQualifiedName(DictionaryFilter dictionaryFilter) {
		return dictionaryFilter.packageName + '.' + dictionaryFilter.dictionaryClassName;
	}

	def dictionaryClassFullQualifiedFileName(DictionaryFilter dictionaryFilter) {
		return dictionaryFilter.dictionaryClassFullQualifiedName.replaceAll("\\.", "/")  + ".java";
	}

	def dictionaryConstantName(DictionaryFilter dictionaryFilter) {
		dictionaryFilter.name.constantName
	}
	
	//-------------------------------------------------------------------------
	// DictionaryResult
	//-------------------------------------------------------------------------
	def dictionaryClassName(DictionaryResult  dictionaryResult) {
		return dictionaryResult.name.toFirstUpper();
	}

	def dictionaryClassFullQualifiedName(DictionaryResult  dictionaryResult) {
		return dictionaryResult.packageName + '.' + dictionaryResult.dictionaryClassName;
	}

	def dictionaryClassFullQualifiedFileName(DictionaryResult  dictionaryResult) {
		return dictionaryResult.dictionaryClassFullQualifiedName.replaceAll("\\.", "/")  + ".java";
	}

	def dictionaryConstantName(DictionaryResult  dictionaryResult) {
		dictionaryResult.name.constantName
	}
	
	//-------------------------------------------------------------------------
	// DictionaryControl
	//-------------------------------------------------------------------------
	def dictionaryClassName(DictionaryControl dictionaryControl) {
		return dictionaryControl.name.toFirstUpper();
	}

	def dictionaryClassFullQualifiedName(DictionaryControl dictionaryControl) {
		return dictionaryControl.packageName + '.' + dictionaryControl.dictionaryClassName;
	}

	def dictionaryClassFullQualifiedFileName(DictionaryControl dictionaryControl) {
		return dictionaryControl.dictionaryClassFullQualifiedName.replaceAll("\\.", "/")  + ".java";
	}

	def dictionaryConstantName(DictionaryControl dictionaryControl) {
		ModelUtil.getControlName(dictionaryControl).constantName
	}
	
	//-------------------------------------------------------------------------
	// DictionaryContainer
	//-------------------------------------------------------------------------
	def dictionaryClassName(DictionaryContainer dictionaryContainer) {
		return dictionaryContainer.name.toFirstUpper();
	}

	def dictionaryClassFullQualifiedName(DictionaryContainer dictionaryContainer) {
		return dictionaryContainer.packageName + '.' + dictionaryContainer.dictionaryClassName;
	}

	def dictionaryClassFullQualifiedFileName(DictionaryContainer dictionaryContainer) {
		return dictionaryContainer.dictionaryClassFullQualifiedName.replaceAll("\\.", "/")  + ".java";
	}

	def dictionaryConstantName(DictionaryContainer dictionaryContainer) {
		dictionaryContainer.name.constantName
	}
}
