/*
* generated by Xtext
*/
package io.pelle.mango.dsl.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class MangoProposalProvider extends io.pelle.mango.dsl.ui.contentassist.AbstractMangoProposalProvider {

	@Override
	public void completeDictionaryEditor_Name(EObject model, Assignment assignment, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {

		String proposal = "ID";
		acceptor.accept(createCompletionProposal(proposal, context));
	}
}
