# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "mango-showcase"
	config.vm.box_url = "https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/14.10/ubuntu-14.10-amd64.box"
	config.vm.network :forwarded_port, guest: 8080, host: 8080
	config.vm.synced_folder ".", "/vagrant", disabled: true

	config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "1024"]
		vb.customize ["modifyvm", :id, "--cpus", "2"]
	end

	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "playbook.yml"
		ansible.verbose = "vvvv"
	end

end
