/**
 * generated by Xtext
 */
package io.pelle.mango.dsl.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class MangoProposalProvider /* implements AbstractMangoProposalProvider  */{
}
