/**
 * generated by Xtext
 */
package io.pelle.mango.dsl.validation;

import io.pelle.mango.dsl.validation.AbstractMangoValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MangoValidator extends AbstractMangoValidator {
}
