/**
 * generated by Xtext
 */
package io.pelle.mango.dsl.validation;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MangoValidator /* implements AbstractMangoValidator  */{
}
